### ISSUE TITLE
按照文档配置环境，但出现了如下的错误

### ISSUE THREAD

**Issue by UsernameRance** [jpzhang1810/TGR#2]
![image](https://github.com/jpzhang1810/TGR/assets/100516489/6aa97541-d3aa-4edc-9012-41e1f0548931)
如果作者能够解决的话，非常感谢

**Comment by jpzhang1810** [comment]
你好，可以看一下你的pytorch版本吗？可能是版本问题。

**Comment by UsernameRance** [comment]
![image](https://github.com/jpzhang1810/TGR/assets/100516489/32155399-1645-4823-a8cd-0c6f34eaa476)
版本是2.0.1，非常感谢

**Comment by HSA-HSA** [comment]
你要把pytorch版本降到1.7.1，应该就能解决。

**Comment by jpzhang1810** [comment]
你要把pytorch版本降到1.7.1，应该就能解决。
